function main_launcher()
    % 信号处理工具统一启动器
    % 版本: 1.0
    % 特性: 模块化、可扩展、配置文件驱动
    
    % 自动初始化路径
    try
        init_project();
    catch ME
        errordlg(['路径初始化失败: ' ME.message], '初始化错误');
        return;
    end
    
    % 创建主窗口
    launcher_fig = figure('Name', 'Signal Processing Tool', ...
                         'Position', [300, 150, 900, 650], ...
                         'MenuBar', 'none', 'ToolBar', 'none', ...
                         'NumberTitle', 'off', 'Resize', 'off', ...
                         'Color', [0.95 0.95 0.95]);
    
    % 加载模块配置
    modules = load_module_config();
    
    % 创建UI
    create_ui(launcher_fig, modules);
end

function modules = load_module_config()
    % 加载模块配置（配置文件驱动，易于扩展）
    % 返回: modules - 模块配置结构体数组
    
    modules = [];
    
    % 模块1: ReadA - 单点信号分析
    modules(1).id = 'module_a';
    modules(1).name = 'Module A';
    modules(1).full_name = 'Single Point Signal Analysis';
    modules(1).description = ['Analyze individual time-domain signals' newline ...
                             '• Load TXT files' newline ...
                             '• Real-time filtering' newline ...
                             '• Time-frequency analysis' newline ...
                             '• Multi-signal comparison'];
    modules(1).icon_color = [0.2 0.6 0.9];
    modules(1).callback = @launch_module_a;
    modules(1).enabled = true;
    
    % 模块2: ReadB - B扫多文件分析
    modules(2).id = 'module_b';
    modules(2).name = 'Module B';
    modules(2).full_name = 'B-Scan Multi-File Analysis';
    modules(2).description = ['Batch process multiple TXT files' newline ...
                             '• Load numbered files (1.txt, 2.txt, ...)' newline ...
                             '• Time domain overlay' newline ...
                             '• Peak-to-peak extraction' newline ...
                             '• Amplitude curve analysis'];
    modules(2).icon_color = [0.9 0.6 0.2];
    modules(2).callback = @launch_module_b;
    modules(2).enabled = true;
    
    % 模块3: ReadC - 波场数据分析
    modules(3).id = 'module_c';
    modules(3).name = 'Module C';
    modules(3).full_name = 'Wave Field Data Analysis';
    modules(3).description = ['Analyze 2D wave field data' newline ...
                             '• Load MAT files' newline ...
                             '• 2D visualization' newline ...
                             '• Point-click analysis' newline ...
                             '• Spatial interpolation' newline ...
                             '• Animation playback'];
    modules(3).icon_color = [0.2 0.7 0.4];
    modules(3).callback = @launch_module_c;
    modules(3).enabled = true;
    
    % 预留扩展位置 - 只需添加新配置即可
    % modules(4).id = 'module_d';
    % modules(4).name = 'Module D';
    % ...
end

function create_ui(fig, modules)
    % 创建用户界面
    
    % === 顶部标题栏 ===
    title_panel = uipanel('Parent', fig, ...
                         'Position', [0.02 0.88 0.96 0.10], ...
                         'BackgroundColor', [0.15 0.25 0.45], ...
                         'BorderType', 'none');
    
    % 主标题
    uicontrol('Parent', title_panel, 'Style', 'text', ...
              'String', 'Signal Processing Tool', ...
              'Position', [20, 30, 400, 35], ...
              'FontSize', 24, 'FontWeight', 'bold', ...
              'ForegroundColor', [1 1 1], ...
              'BackgroundColor', [0.15 0.25 0.45], ...
              'HorizontalAlignment', 'left');
    
    % 副标题
    uicontrol('Parent', title_panel, 'Style', 'text', ...
              'String', 'Ultrasonic Signal Analysis Platform', ...
              'Position', [20, 10, 300, 20], ...
              'FontSize', 11, 'FontAngle', 'italic', ...
              'ForegroundColor', [0.8 0.85 0.95], ...
              'BackgroundColor', [0.15 0.25 0.45], ...
              'HorizontalAlignment', 'left');
    
    % 版本信息
    uicontrol('Parent', title_panel, 'Style', 'text', ...
              'String', 'v2.0', ...
              'Position', [800, 30, 60, 25], ...
              'FontSize', 12, ...
              'ForegroundColor', [0.7 0.8 0.9], ...
              'BackgroundColor', [0.15 0.25 0.45]);
    
    % === 模块选择区域 ===
    modules_panel = uipanel('Parent', fig, ...
                           'Position', [0.02 0.30 0.96 0.56], ...
                           'Title', 'Select Analysis Module', ...
                           'FontSize', 13, 'FontWeight', 'bold', ...
                           'BackgroundColor', [0.95 0.95 0.95]);
    
    % 修复: 动态创建模块按钮 - 确保按钮正确创建
    num_modules = length(modules);
    cols = 3;  % 每行3个模块
    rows = ceil(num_modules / cols);
    
    button_width = 260;
    button_height = 140;
    spacing_h = 30;
    spacing_v = 30;
    
    % 计算起始位置（居中对齐）
    total_width = cols * button_width + (cols-1) * spacing_h;
    start_x = (900 * 0.96 - total_width) / 2;
    
    % 从上往下布局
    panel_height = 650 * 0.56;
    start_y = panel_height - button_height - 40;
    
    for i = 1:num_modules
        row = floor((i - 1) / cols);
        col = mod(i - 1, cols);
        
        x = start_x + col * (button_width + spacing_h);
        y = start_y - row * (button_height + spacing_v);
        
        create_module_button(modules_panel, modules(i), x, y, button_width, button_height);
    end
    
    % === 底部信息栏 ===
    info_panel = uipanel('Parent', fig, ...
                        'Position', [0.02 0.12 0.96 0.16], ...
                        'Title', 'Quick Start Guide', ...
                        'FontSize', 12, 'FontWeight', 'bold', ...
                        'BackgroundColor', [0.95 0.95 0.95]);
    
    guide_text = sprintf(['Welcome to Signal Processing Tool!\n\n' ...
                         '1. Select a module above to begin analysis\n' ...
                         '2. Each module is optimized for specific data types\n' ...
                         '3. All modules share the same core analysis engine\n' ...
                         '4. Use Settings to customize default parameters']);
    
    uicontrol('Parent', info_panel, 'Style', 'text', ...
              'String', guide_text, ...
              'Position', [20, 10, 600, 75], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95 0.95 0.95]);
    
    % === 底部按钮区域 ===
    button_panel = uipanel('Parent', fig, ...
                          'Position', [0.02 0.02 0.96 0.08], ...
                          'BorderType', 'none', ...
                          'BackgroundColor', [0.95 0.95 0.95]);
    
    % 设置按钮
    uicontrol('Parent', button_panel, 'Style', 'pushbutton', ...
              'String', '⚙ Settings', ...
              'Position', [20, 10, 120, 35], ...
              'FontSize', 11, ...
              'BackgroundColor', [0.9 0.9 0.9], ...
              'Callback', @open_settings);
    
    % 帮助按钮
    uicontrol('Parent', button_panel, 'Style', 'pushbutton', ...
              'String', '? Help', ...
              'Position', [150, 10, 120, 35], ...
              'FontSize', 11, ...
              'BackgroundColor', [0.9 0.9 0.9], ...
              'Callback', @open_help);
    
    % 关于按钮
    uicontrol('Parent', button_panel, 'Style', 'pushbutton', ...
              'String', 'ⓘ About', ...
              'Position', [280, 10, 120, 35], ...
              'FontSize', 11, ...
              'BackgroundColor', [0.9 0.9 0.9], ...
              'Callback', @show_about);
    
    % 退出按钮
    uicontrol('Parent', button_panel, 'Style', 'pushbutton', ...
              'String', 'Exit', ...
              'Position', [760, 10, 100, 35], ...
              'FontSize', 11, ...
              'BackgroundColor', [1.0 0.85 0.85], ...
              'Callback', @(~,~) close(fig));
end

function create_module_button(parent, module, x, y, width, height)
    % 创建单个模块按钮
    
    % 创建按钮面板
    btn_panel = uipanel('Parent', parent, ...
                       'Units', 'pixels', ...  % 修复: 使用像素单位
                       'Position', [x, y, width, height], ...
                       'BackgroundColor', [1 1 1], ...
                       'BorderType', 'line', ...
                       'HighlightColor', module.icon_color, ...
                       'BorderWidth', 2);
    
    % 模块图标区域（顶部色块）
    icon_height = height * 0.35;
    icon_panel = uipanel('Parent', btn_panel, ...
                        'Units', 'pixels', ...
                        'Position', [0, height - icon_height, width, icon_height], ...
                        'BackgroundColor', module.icon_color, ...
                        'BorderType', 'none');
    
    % 模块名称（大号）
    uicontrol('Parent', icon_panel, 'Style', 'text', ...
              'String', module.name, ...
              'Units', 'pixels', ...
              'Position', [10, 15, width-20, 30], ...
              'FontSize', 18, 'FontWeight', 'bold', ...
              'ForegroundColor', [1 1 1], ...
              'BackgroundColor', module.icon_color, ...
              'HorizontalAlignment', 'center');
    
    % 全名标题
    uicontrol('Parent', btn_panel, 'Style', 'text', ...
              'String', module.full_name, ...
              'Units', 'pixels', ...
              'Position', [10, height - icon_height - 25, width-20, 20], ...
              'FontSize', 11, 'FontWeight', 'bold', ...
              'HorizontalAlignment', 'center', ...
              'BackgroundColor', [1 1 1]);
    
    % 功能描述
    uicontrol('Parent', btn_panel, 'Style', 'text', ...
              'String', module.description, ...
              'Units', 'pixels', ...
              'Position', [10, 40, width-20, 50], ...
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [1 1 1]);
    
    % 启动按钮
    if module.enabled
        btn_color = module.icon_color;
        btn_text = 'Launch';
        btn_callback = module.callback;
    else
        btn_color = [0.7 0.7 0.7];
        btn_text = 'Coming Soon';
        btn_callback = @(~,~) msgbox('This module is under development', 'Info');
    end
    
    uicontrol('Parent', btn_panel, 'Style', 'pushbutton', ...
              'String', btn_text, ...
              'Units', 'pixels', ...
              'Position', [width/2-50, 5, 100, 30], ...
              'FontSize', 10, 'FontWeight', 'bold', ...
              'BackgroundColor', btn_color, ...
              'ForegroundColor', [1 1 1], ...
              'Callback', btn_callback);
end

%% 模块启动函数

function launch_module_a(~, ~)
    % 启动模块A
    try
        fprintf('\n启动模块A: 单点信号分析...\n');
        ReadA();
    catch ME
        errordlg(['Failed to launch Module A: ' ME.message], 'Launch Error');
    end
end

function launch_module_b(~, ~)
    % 启动模块B
    try
        fprintf('\n启动模块B: B扫多文件分析...\n');
        ReadB();
    catch ME
        errordlg(['Failed to launch Module B: ' ME.message], 'Launch Error');
    end
end

function launch_module_c(~, ~)
    % 启动模块C
    try
        fprintf('\n启动模块C: 波场数据分析...\n');
        ReadC();
    catch ME
        errordlg(['Failed to launch Module C: ' ME.message], 'Launch Error');
    end
end

%% 辅助功能函数

function open_settings(~, ~)
    % 打开设置对话框
    settings_fig = figure('Name', 'Settings', ...
                         'Position', [400, 250, 500, 400], ...
                         'MenuBar', 'none', 'ToolBar', 'none', ...
                         'NumberTitle', 'off', 'Resize', 'off');
    
    uicontrol('Parent', settings_fig, 'Style', 'text', ...
              'String', 'Application Settings', ...
              'Position', [20, 350, 460, 30], ...
              'FontSize', 14, 'FontWeight', 'bold');
    
    % 默认滤波器设置
    uicontrol('Parent', settings_fig, 'Style', 'text', ...
              'String', 'Default Filter Settings:', ...
              'Position', [20, 310, 200, 20], ...
              'HorizontalAlignment', 'left', 'FontWeight', 'bold');
    
    uicontrol('Parent', settings_fig, 'Style', 'text', ...
              'String', 'Low Frequency (kHz):', ...
              'Position', [40, 280, 150, 20], ...
              'HorizontalAlignment', 'left');
    uicontrol('Parent', settings_fig, 'Style', 'edit', ...
              'String', '100', ...
              'Position', [200, 280, 80, 25]);
    
    uicontrol('Parent', settings_fig, 'Style', 'text', ...
              'String', 'High Frequency (kHz):', ...
              'Position', [40, 250, 150, 20], ...
              'HorizontalAlignment', 'left');
    uicontrol('Parent', settings_fig, 'Style', 'edit', ...
              'String', '500', ...
              'Position', [200, 250, 80, 25]);
    
    % 主题设置
    uicontrol('Parent', settings_fig, 'Style', 'text', ...
              'String', 'Theme:', ...
              'Position', [20, 210, 200, 20], ...
              'HorizontalAlignment', 'left', 'FontWeight', 'bold');
    
    uicontrol('Parent', settings_fig, 'Style', 'popupmenu', ...
              'String', {'Default', 'Dark', 'Light'}, ...
              'Position', [40, 180, 150, 25]);
    
    % 按钮
    uicontrol('Parent', settings_fig, 'Style', 'pushbutton', ...
              'String', 'Save', ...
              'Position', [280, 20, 100, 35], ...
              'BackgroundColor', [0.8 0.9 1.0], ...
              'Callback', @(~,~) save_settings(settings_fig));
    
    uicontrol('Parent', settings_fig, 'Style', 'pushbutton', ...
              'String', 'Cancel', ...
              'Position', [390, 20, 100, 35], ...
              'Callback', @(~,~) close(settings_fig));
end

function save_settings(fig)
    % 保存设置
    msgbox('Settings saved successfully!', 'Success');
    close(fig);
end

function open_help(~, ~)
    % 打开帮助文档
    help_fig = figure('Name', 'Help Documentation', ...
                     'Position', [350, 200, 700, 500], ...
                     'MenuBar', 'none', 'ToolBar', 'none', ...
                     'NumberTitle', 'off');
    
    help_text = sprintf(['Signal Processing Tool - User Guide\n\n' ...
                        '=== Module A: Single Point Analysis ===\n' ...
                        '1. Browse and load TXT files\n' ...
                        '2. Apply filters (High-pass, Low-pass, Band-pass)\n' ...
                        '3. View time-frequency analysis\n' ...
                        '4. Compare multiple signals\n\n' ...
                        '=== Module B: B-Scan Analysis ===\n' ...
                        '1. Select folder with numbered files (1.txt, 2.txt, ...)\n' ...
                        '2. Adjust time range for analysis\n' ...
                        '3. Extract peak-to-peak amplitudes\n' ...
                        '4. View amplitude curves\n\n' ...
                        '=== Module C: Wave Field Analysis ===\n' ...
                        '1. Load MAT files with wave field data\n' ...
                        '2. Set grid parameters (m × n)\n' ...
                        '3. Click on field to analyze specific points\n' ...
                        '4. Use interpolation to enhance resolution\n' ...
                        '5. Play animation to see wave propagation\n\n' ...
                        'For more information, visit the documentation folder.']);
    
    uicontrol('Parent', help_fig, 'Style', 'text', ...
              'String', help_text, ...
              'Position', [20, 50, 660, 420], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95 0.95 0.95]);
    
    uicontrol('Parent', help_fig, 'Style', 'pushbutton', ...
              'String', 'Close', ...
              'Position', [300, 10, 100, 30], ...
              'Callback', @(~,~) close(help_fig));
end

function show_about(~, ~)
    % 显示关于信息
    about_msg = sprintf(['Signal Processing Tool v2.0\n\n' ...
                        'Ultrasonic Signal Analysis Platform\n\n' ...
                        'Features:\n' ...
                        '• Single point signal analysis\n' ...
                        '• B-scan multi-file processing\n' ...
                        '• Wave field visualization\n' ...
                        '• Advanced filtering and analysis\n\n' ...
                        'Architecture:\n' ...
                        '• Modular design\n' ...
                        '• Plugin-based extensibility\n' ...
                        '• Unified core engine\n\n' ...
                        'Developed with MATLAB\n' ...
                        'Copyright © 2024']);
    
    msgbox(about_msg, 'About Signal Processing Tool', 'help');
end
